//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Sale_Indent
    {
        public int CSI_id { get; set; }
        public string CSI_Number { get; set; }
        public string DC_Code { get; set; }
        public Nullable<System.DateTime> CSI_Raised_date { get; set; }
        public Nullable<System.DateTime> CSI_Timestamp { get; set; }
        public Nullable<int> SKU_Type_Id { get; set; }
        public string CSI_From { get; set; }
        public string SKU_Type { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public string Customer_Code { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<int> Delivery_Location_ID { get; set; }
        public string Delivery_Location_Code { get; set; }
        public string Delivery_cycle { get; set; }
        public Nullable<System.DateTime> Delivery_Expected_Date { get; set; }
        public string Delievery_Type { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public string CSI_raised_by { get; set; }
        public Nullable<bool> CSI_Approved_Flag { get; set; }
        public string CSI_Approved_by { get; set; }
        public Nullable<System.DateTime> CSI_Approved_date { get; set; }
        public string Status { get; set; }
        public Nullable<int> Multiple_CSI_tracking_id_FK { get; set; }
        public string Reason { get; set; }
        public bool is_Deleted { get; set; }
        public Nullable<int> CSI_Create_by { get; set; }
        public string CSI_type { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> Indent_Id { get; set; }
        public string Indent_Name { get; set; }
        public Nullable<int> Rate_Template_Id { get; set; }
        public string Rate_Template_Name { get; set; }
        public Nullable<bool> is_Syunc { get; set; }
        public Nullable<System.DateTime> Rate_Template_Valitity_upto { get; set; }
        public Nullable<int> User_Location_Id { get; set; }
        public string User_Location_Code { get; set; }
        public string User_Location { get; set; }
        public string User_Type { get; set; }
        public string Rate_Template_Code { get; set; }
        public string Indent_Code { get; set; }
        public Nullable<int> Expected_Route_Id { get; set; }
        public string Expected_Route_Alias_Name { get; set; }
        public string Expected_Route_Code { get; set; }
        public Nullable<int> Expected_Delivering_Sales_Person_Id { get; set; }
        public string Expected_Delivering_Sales_Person_Name { get; set; }
    }
}
