//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Indent
    {
        public int Indent_ID { get; set; }
        public string Indent_Name { get; set; }
        public Nullable<int> DC_Id { get; set; }
        public string DC_Code { get; set; }
        public Nullable<int> Location_Id { get; set; }
        public string Location_Code { get; set; }
        public Nullable<int> Region_Id { get; set; }
        public string Region { get; set; }
        public string Indent_Type { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Code { get; set; }
        public string Customer_Delivery_Address { get; set; }
        public string Dispatch_DC_Code { get; set; }
        public string Delivery_cycle { get; set; }
        public Nullable<System.DateTime> Delivery_Expected_Date { get; set; }
        public string Delivery_Type { get; set; }
        public Nullable<int> SKU_Type_Id { get; set; }
        public string SKU_Type { get; set; }
        public Nullable<int> Price_Template_ID { get; set; }
        public string Price_Template_Name { get; set; }
        public Nullable<System.DateTime> Price_Template_Valitity_upto { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public string Region_Code { get; set; }
        public string Indent_Code { get; set; }
        public string Price_Template_Code { get; set; }
        public Nullable<bool> Is_Sync { get; set; }
    }
}
