//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCDASHBOARD_PO
    {
        public string DC_Code { get; set; }
        public Nullable<int> No_of_PO { get; set; }
        public Nullable<int> No_of_Supplier_name { get; set; }
        public Nullable<double> TOTAL_Qty { get; set; }
    }
}
