//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch_Line_item
    {
        public int Dispatch_Line_Id { get; set; }
        public Nullable<int> Dispatch_Id { get; set; }
        public Nullable<int> SKU_ID { get; set; }
        public string SKU_Code { get; set; }
        public string SKU_Name { get; set; }
        public Nullable<int> Supplier_Id { get; set; }
        public string Supplier_Name { get; set; }
        public string Supplier_Code { get; set; }
        public Nullable<int> SKU_SubType_Id { get; set; }
        public string SKU_SubType { get; set; }
        public Nullable<int> Pack_Type_Id { get; set; }
        public string Pack_Size { get; set; }
        public Nullable<int> Pack_Weight_Type_Id { get; set; }
        public string Pack_Weight_Type { get; set; }
        public string UOM { get; set; }
        public Nullable<double> Strinkage_Qty { get; set; }
        public Nullable<double> Indent_Qty { get; set; }
        public Nullable<double> Dispatch_Qty { get; set; }
        public string Grade { get; set; }
        public Nullable<double> Return_Qty { get; set; }
        public Nullable<double> Received_Qty { get; set; }
        public Nullable<double> Accepted_Qty { get; set; }
        public Nullable<double> Unit_Rate { get; set; }
        public Nullable<double> Dispatch_Value { get; set; }
        public Nullable<double> No_of_Packed_Item { get; set; }
        public string Pack_Type { get; set; }
        public string Acceptance_Status { get; set; }
        public string Dispatch_Pack_Type { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public Nullable<bool> is_Deleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<bool> is_Stk_Update { get; set; }
        public Nullable<double> Converted_Unit_Value { get; set; }
        public string Tally_Status { get; set; }
        public Nullable<int> Master_Id { get; set; }
        public string HSN_Code { get; set; }
        public Nullable<double> Total_GST { get; set; }
        public Nullable<double> CGST { get; set; }
        public Nullable<double> SGST { get; set; }
    }
}
