//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch_Consumables
    {
        public int Dispatch_Consumables_Id { get; set; }
        public Nullable<int> Dispatch_Line_Id_FK { get; set; }
        public Nullable<int> Dispatch_SKU_Line_Items_Id_FK { get; set; }
        public Nullable<int> SKU_Id { get; set; }
        public Nullable<double> Consumable_Qty { get; set; }
        public string Grade { get; set; }
        public string UOM { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> is_Deleted { get; set; }
    }
}
