//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerciseTable
    {
        public int ID { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> menuid { get; set; }
        public string idsString { get; set; }
    }
}
