//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Creation
    {
        public int invoice_Id { get; set; }
        public string Invoice_Number { get; set; }
        public Nullable<int> Dispatch_id { get; set; }
        public string Customer_Dispatch_Number { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public string Invoice_Type { get; set; }
        public Nullable<int> SKU_Type_Id { get; set; }
        public string SKU_Type { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public string Customer_code { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<int> DC_ID { get; set; }
        public string DC_Code { get; set; }
        public string Term_of_Payment { get; set; }
        public string Supplier_Ref { get; set; }
        public string Buyer_Order_No { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<bool> is_Deleted { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> is_Invoice_Approved { get; set; }
        public Nullable<int> is_Invoice_approved_user_id { get; set; }
        public string is_Invoice_approved_by { get; set; }
        public Nullable<System.DateTime> is_Invoice_approved_date { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<bool> is_Syunc { get; set; }
        public string Order_Reference { get; set; }
    
        public virtual Invoice_Creation Invoice_Creation1 { get; set; }
        public virtual Invoice_Creation Invoice_Creation2 { get; set; }
    }
}
