//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printed_Barcode_Details
    {
        public int Printed_Barcode_ID { get; set; }
        public string Generated_Bar_Code { get; set; }
        public string DC_Code { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public string Customer_Name { get; set; }
        public string Template_Id { get; set; }
        public string Template_Name { get; set; }
        public string Product_Type { get; set; }
        public Nullable<System.DateTime> Packed_On { get; set; }
        public string Best_Before { get; set; }
        public Nullable<int> Number_Of_Copies { get; set; }
        public string FSSAI { get; set; }
        public Nullable<int> SKU_Id { get; set; }
        public string SKU_Name { get; set; }
        public string SKU_Leaf_flag { get; set; }
        public string UOM { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string EAN { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> is_Deleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Updated_By { get; set; }
    }
}
