//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Order
    {
        public int Po_id { get; set; }
        public string PO_Number { get; set; }
        public string DC_Code { get; set; }
        public Nullable<System.DateTime> PO_RLS_date { get; set; }
        public Nullable<int> Material_Source_id { get; set; }
        public string Material_Source { get; set; }
        public Nullable<int> Supplier_Id { get; set; }
        public string Supplier_Code { get; set; }
        public string Supplier_name { get; set; }
        public string PO_Requisitioned_by { get; set; }
        public string PO_Type { get; set; }
        public string Payment_cycle { get; set; }
        public string Payment_type { get; set; }
        public Nullable<int> SKU_Type_Id { get; set; }
        public string SKU_Type { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public string PO_raise_by { get; set; }
        public string PO_Approve_by { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string Status { get; set; }
        public Nullable<bool> PO_Approval_Flag { get; set; }
        public Nullable<System.DateTime> PO_Approved_date { get; set; }
        public Nullable<bool> is_Deleted { get; set; }
        public string Reason { get; set; }
        public string Delete_Reason { get; set; }
        public Nullable<bool> is_Syunc { get; set; }
    
        public virtual Purchase_Order Purchase_Order1 { get; set; }
        public virtual Purchase_Order Purchase_Order2 { get; set; }
    }
}
