//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate_Template
    {
        public int Template_ID { get; set; }
        public string Template_Name { get; set; }
        public Nullable<int> DC_Id { get; set; }
        public string DC_Code { get; set; }
        public Nullable<int> Location_Id { get; set; }
        public string Location_Code { get; set; }
        public Nullable<int> Region_Id { get; set; }
        public string Region { get; set; }
        public Nullable<int> SKU_Type_Id { get; set; }
        public string SKU_Type { get; set; }
        public string Customer_Category { get; set; }
        public Nullable<System.DateTime> Valitity_upto { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public string Customer_Category_Code { get; set; }
        public string Region_Code { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public string SKU_Type_Code { get; set; }
        public string Template_Code { get; set; }
        public Nullable<bool> Is_JDM_Synced { get; set; }
        public Nullable<bool> Is_BNG_Synced { get; set; }
    }
}
