//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_DISPATCH_PACKTYPE_BASED
    {
        public Nullable<int> Number_of_SKU { get; set; }
        public string Delivery_Location_Code { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SKU_Category { get; set; }
        public double Branded_Retail { get; set; }
        public double Branded_Bulk { get; set; }
        public double Un_Branded_Bulk { get; set; }
        public double Total { get; set; }
    }
}
