//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_STI_DISPATCH
    {
        public string Material_Source { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SKU_Category { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Dispatch_Qty { get; set; }
        public Nullable<double> Fill_Rate { get; set; }
    }
}
