//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_DISPATCH
    {
        public string Delivery_Location_Code { get; set; }
        public Nullable<int> No_SKU { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SKU_Category { get; set; }
        public double A { get; set; }
        public double B { get; set; }
        public double Total_qty { get; set; }
    }
}
