//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_CUSTOMER_FILL_RATE
    {
        public string DC_Code { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int Modern_Retail { get; set; }
        public int General_Trade { get; set; }
        public int Distributor { get; set; }
        public int Exporter { get; set; }
        public int HORECA { get; set; }
        public int Market_Sale { get; set; }
        public int Wholesaler { get; set; }
        public int DC_Sale { get; set; }
        public string Type { get; set; }
    }
}
