//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_MONTH_BASED_ORDER
    {
        public string DC_Code { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Category { get; set; }
        public Nullable<int> Total_Count { get; set; }
        public string Type { get; set; }
    }
}
