//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route_Master_Auto_Num_Gen
    {
        public int Route_Master_Auto_Gen_Id { get; set; }
        public string Route_Prefix { get; set; }
        public Nullable<int> Route_Last_No { get; set; }
    }
}
