//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKU_Main_Sub_Mapping
    {
        public int SKU_mapping__Id { get; set; }
        public Nullable<int> SKU_Id { get; set; }
        public Nullable<int> SKU_Main_Group_Id { get; set; }
        public Nullable<int> SKU_Sub_Group_Id { get; set; }
    }
}
