//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKU_Master
    {
        public string SKU_Name { get; set; }
        public string Material_Code { get; set; }
        public string SKU_Category { get; set; }
        public int SKU_Id { get; set; }
        public string SKU_Code { get; set; }
        public string Receiving_JDP { get; set; }
        public string UOM { get; set; }
        public string Chennai_Alias { get; set; }
        public string Coimbatore_Alias { get; set; }
        public string Ooty_Alias { get; set; }
        public string Bangalore_Alias { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string Tally_Status { get; set; }
        public string HSN_Code { get; set; }
        public Nullable<double> Total_GST { get; set; }
        public Nullable<double> CGST { get; set; }
        public Nullable<double> SGST { get; set; }
    }
}
