//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Transaction
    {
        public int ST_Tran_ID { get; set; }
        public string Stock_Code { get; set; }
        public Nullable<int> INW_id { get; set; }
        public string GRN_Number { get; set; }
        public Nullable<int> GRN_Line_Id { get; set; }
        public string SKU_Code { get; set; }
        public string SKU_Name { get; set; }
        public string SKU_Type { get; set; }
        public Nullable<int> SKU_Type_Id { get; set; }
        public string Supplier_Code { get; set; }
        public string Supplier_Name { get; set; }
        public Nullable<double> Qty { get; set; }
        public string UOM { get; set; }
        public string Grade { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public string DC_Code { get; set; }
    
        public virtual Stock_Transaction Stock_Transaction1 { get; set; }
        public virtual Stock_Transaction Stock_Transaction2 { get; set; }
    }
}
