//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Strinkage_Stock_Adjustement
    {
        public int Strinkage_Stock_Adjustement_Id { get; set; }
        public string Adjustment_Batch_Code { get; set; }
        public Nullable<int> Stirnkage_Summary_Id_FK { get; set; }
        public Nullable<int> Stock_Id { get; set; }
        public string Material_Code { get; set; }
        public string Stock_code { get; set; }
        public string DC_Code { get; set; }
        public string DC_Name { get; set; }
        public string SKU_Code { get; set; }
        public string SKU_Name { get; set; }
        public Nullable<int> SKU_Type_Id { get; set; }
        public string SKU_Type { get; set; }
        public Nullable<double> System_Stock_Qty { get; set; }
        public Nullable<double> Closing_Qty { get; set; }
        public Nullable<double> Strinkage_Qty { get; set; }
        public Nullable<System.DateTime> Close_Date { get; set; }
        public string UOM { get; set; }
        public string Grade { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
    }
}
