//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public string Supplier_Name { get; set; }
        public string City { get; set; }
        public int Supplier_ID { get; set; }
        public string Supplier_code { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string Primary_Contact_Name { get; set; }
        public Nullable<long> Contact_Number { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string Secondary_Email_ID { get; set; }
        public string Primary_Email_ID { get; set; }
        public string Location { get; set; }
        public string Location_Code { get; set; }
        public Nullable<bool> is_Syunc { get; set; }
        public Nullable<int> Collection_Centre_Id { get; set; }
        public string Collection_Centre { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Father_Name { get; set; }
        public string PAN_Number { get; set; }
        public string Bank_Name { get; set; }
        public Nullable<long> Bank_Account_Number { get; set; }
        public Nullable<int> Payment_Type_Id { get; set; }
        public string Payment_Type { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> Supplier_Activation_Date { get; set; }
        public string Supplier_IDCard_Number { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
        public string Farm_location { get; set; }
        public string Farm_Area { get; set; }
        public string Tally_Status { get; set; }
    }
}
