//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Code_Num_Gen
    {
        public int Supplier_Num_Gen_Id { get; set; }
        public Nullable<int> Stock_Last_Number { get; set; }
    }
}
