//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wastage_Line_item
    {
        public int Wastage_Line_Id { get; set; }
        public Nullable<int> Wastage_Id { get; set; }
        public string Wastage_Number { get; set; }
        public Nullable<int> SKU_ID { get; set; }
        public string SKU_Code { get; set; }
        public string SKU_Name { get; set; }
        public Nullable<int> Ref_Id { get; set; }
        public Nullable<int> Ref_Line_Id { get; set; }
        public Nullable<int> SKU_Type_Id { get; set; }
        public string SKU_Type { get; set; }
        public string UOM { get; set; }
        public Nullable<double> Wastage_Qty { get; set; }
        public Nullable<double> Wasted_Qty_Price { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> Stock_Reduce_Flag { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string Grade { get; set; }
        public Nullable<bool> is_Stk_Update { get; set; }
        public string Tally_Status { get; set; }
    }
}
