//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wastage_Auto_Num_Gen
    {
        public int Id { get; set; }
        public string DC_Code { get; set; }
        public Nullable<int> Wastage_Last_Number { get; set; }
    }
}
