//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wastage_Creation
    {
        public int Wastage_Id { get; set; }
        public string Wastage_Number { get; set; }
        public Nullable<int> DC_Id { get; set; }
        public string DC_Code { get; set; }
        public string DC_Name { get; set; }
        public Nullable<int> Ref_Id { get; set; }
        public string Ref_Number { get; set; }
        public string Wastage_Type { get; set; }
        public string Wastage_raisedBy { get; set; }
        public Nullable<System.DateTime> Wastage_Rls_Date { get; set; }
        public Nullable<bool> is_Deleted { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Wastage_Approval_Flag { get; set; }
        public Nullable<int> Wastage_approved_user_id { get; set; }
        public string Wastage_approved_by { get; set; }
        public string Reject_Reason { get; set; }
        public Nullable<System.DateTime> Wastage_approved_date { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> is_Syunc { get; set; }
    }
}
