//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_Customer_Mapping
    {
        public Nullable<int> Cust_Id { get; set; }
        public string Cust_Name { get; set; }
        public int Dc_Cust_map_Id { get; set; }
        public Nullable<int> DC_id { get; set; }
        public string DC_Code { get; set; }
        public string Cust_Code { get; set; }
    }
}
