//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_Supplier_Mapping
    {
        public Nullable<int> Supplier_ID { get; set; }
        public string Supplier__Name { get; set; }
        public int Dc_Supplier_map_Id { get; set; }
        public Nullable<int> DC_id { get; set; }
        public string Supplier_Code { get; set; }
        public string DC_Code { get; set; }
    }
}
