//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCDASHBOARD_CSISTIADD
    {
        public string DC_Code { get; set; }
        public Nullable<int> Total_Orders { get; set; }
        public double Total_Qty { get; set; }
        public int Dispatched_orders { get; set; }
        public double Dispatched_qty { get; set; }
    }
}
