//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCDASHBOARD_CSI2_CUST_PERCENTBASE
    {
        public string DC_Code { get; set; }
        public Nullable<int> Sku_Count { get; set; }
        public Nullable<int> No_of_CSI_ORDER { get; set; }
        public Nullable<int> Customer_count { get; set; }
    }
}
