//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch_Supplier_Track
    {
        public int Dispatch_Track_Id { get; set; }
        public int Dispatch_Id { get; set; }
        public string Dispatch_Number { get; set; }
        public Nullable<int> Dispatch_Line_Id { get; set; }
        public Nullable<int> INW_id { get; set; }
        public string GRN_Number { get; set; }
        public Nullable<int> GRN_Line_Id { get; set; }
        public Nullable<int> Stock_ID { get; set; }
        public string Stock_code { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public string Supplier { get; set; }
        public Nullable<int> SKU_ID { get; set; }
        public string SKU_Code { get; set; }
        public string SKU_name { get; set; }
        public string Grade { get; set; }
        public Nullable<int> SKU_Type_Id { get; set; }
        public string SKU_Type { get; set; }
        public Nullable<int> SKU_SubType_Id { get; set; }
        public string SKU_SubType { get; set; }
        public Nullable<int> Pack_Type_Id { get; set; }
        public string Pack_Type { get; set; }
        public string Pack_Size { get; set; }
        public Nullable<int> Pack_Weight_Type_Id { get; set; }
        public string Pack_Weight_Type { get; set; }
        public Nullable<double> QTY { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Billed_Qty { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateBy { get; set; }
        public string Dispatch_pack_Type { get; set; }
    
        public virtual Dispatch_Supplier_Track Dispatch_Supplier_Track1 { get; set; }
        public virtual Dispatch_Supplier_Track Dispatch_Supplier_Track2 { get; set; }
    }
}
