//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRN_Creation
    {
        public int INW_Id { get; set; }
        public string GRN_Number { get; set; }
        public string PO_Number { get; set; }
        public string CDN_Number { get; set; }
        public Nullable<System.DateTime> GRN_Rls_Date { get; set; }
        public Nullable<int> STN_DC_Id { get; set; }
        public string STN_DC_Code { get; set; }
        public string STN_DC_Name { get; set; }
        public string Vehicle_No { get; set; }
        public Nullable<int> Sales_Person_Id { get; set; }
        public string Sales_Person_Name { get; set; }
        public Nullable<int> Route_Id { get; set; }
        public string Route_Code { get; set; }
        public string Route { get; set; }
        public string Tally_Status { get; set; }
        public string Voucher_Type { get; set; }
        public Nullable<int> SKU_Type_Id { get; set; }
        public string SKU_Type { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public string Customer_code { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<int> Supplier_Id { get; set; }
        public string Supplier_code { get; set; }
        public string Supplier_Name { get; set; }
        public string DC_Code { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> is_Deleted { get; set; }
        public Nullable<bool> is_Syunc { get; set; }
    }
}
