//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Collection_Excel_Tracking
    {
        public int INV_Collection_Excel_Tracking_id { get; set; }
        public Nullable<int> No_of_Items { get; set; }
        public string Uploaded_Excel_Display_Name { get; set; }
        public string Uploaded_Excel_Name { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public string UploadedBy { get; set; }
    }
}
