//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Collection_Tracking
    {
        public int INV_Collection_Tracking_Id { get; set; }
        public string INV_Collection_Number { get; set; }
        public Nullable<int> DC_id { get; set; }
        public string DC_Code { get; set; }
        public string DC_Name { get; set; }
        public Nullable<int> Sales_Person_Id { get; set; }
        public string Sales_Person_Name { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public string Customer_Code { get; set; }
        public string Customer_Name { get; set; }
        public string INVOICE_Number { get; set; }
        public Nullable<double> INVOICE_Amount { get; set; }
        public Nullable<double> Collected_Amount { get; set; }
        public Nullable<double> OutStanding_Amount { get; set; }
        public Nullable<System.DateTime> INVOICE_Date { get; set; }
        public string Action { get; set; }
        public string Action_DoneBy { get; set; }
        public Nullable<System.DateTime> Date_Of_Action { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<bool> is_Deleted { get; set; }
    }
}
