//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LEAFDBEntities : DbContext
    {
        public LEAFDBEntities()
            : base("name=LEAFDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barcode_Fields_Order> Barcode_Fields_Order { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CSI_Line_item> CSI_Line_item { get; set; }
        public virtual DbSet<CSI_NUM_Generation> CSI_NUM_Generation { get; set; }
        public virtual DbSet<Customer_Code_Num_Gen> Customer_Code_Num_Gen { get; set; }
        public virtual DbSet<Customer_Dispatch_Num_Gen> Customer_Dispatch_Num_Gen { get; set; }
        public virtual DbSet<Customer_Indent> Customer_Indent { get; set; }
        public virtual DbSet<Customer_Indent_Line_item> Customer_Indent_Line_item { get; set; }
        public virtual DbSet<Customer_Indent_Num_Gen> Customer_Indent_Num_Gen { get; set; }
        public virtual DbSet<Customer_Indent_Template_Mapping> Customer_Indent_Template_Mapping { get; set; }
        public virtual DbSet<Customer_Label_Auto_Num_Gen> Customer_Label_Auto_Num_Gen { get; set; }
        public virtual DbSet<Customer_Label_Template> Customer_Label_Template { get; set; }
        public virtual DbSet<Customer_LabelTemplate_Mapping> Customer_LabelTemplate_Mapping { get; set; }
        public virtual DbSet<Customer_Rate_Template_Mapping> Customer_Rate_Template_Mapping { get; set; }
        public virtual DbSet<Customer_Registration> Customer_Registration { get; set; }
        public virtual DbSet<Customer_Sale_Indent> Customer_Sale_Indent { get; set; }
        public virtual DbSet<Customer_SKU_Mapping> Customer_SKU_Mapping { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DC_Customer_Mapping> DC_Customer_Mapping { get; set; }
        public virtual DbSet<DC_Master> DC_Master { get; set; }
        public virtual DbSet<DC_Supplier_Mapping> DC_Supplier_Mapping { get; set; }
        public virtual DbSet<DCK_Table> DCK_Table { get; set; }
        public virtual DbSet<Delivery_Cycle> Delivery_Cycle { get; set; }
        public virtual DbSet<DeliveryAddress> DeliveryAddresses { get; set; }
        public virtual DbSet<Dispatch_Consumables> Dispatch_Consumables { get; set; }
        public virtual DbSet<Dispatch_Creation> Dispatch_Creation { get; set; }
        public virtual DbSet<Dispatch_Line_item> Dispatch_Line_item { get; set; }
        public virtual DbSet<Dispatch_NUM_Generation> Dispatch_NUM_Generation { get; set; }
        public virtual DbSet<Dispatch_SKU_Line_Items> Dispatch_SKU_Line_Items { get; set; }
        public virtual DbSet<Dispatch_Supplier_Track> Dispatch_Supplier_Track { get; set; }
        public virtual DbSet<Estimated_Stock> Estimated_Stock { get; set; }
        public virtual DbSet<Estimated_Stock_NUM_Generation> Estimated_Stock_NUM_Generation { get; set; }
        public virtual DbSet<ExerciseTable> ExerciseTables { get; set; }
        public virtual DbSet<GRN_Consumables> GRN_Consumables { get; set; }
        public virtual DbSet<GRN_Creation> GRN_Creation { get; set; }
        public virtual DbSet<GRN_Line_item> GRN_Line_item { get; set; }
        public virtual DbSet<GRN_NUM_Generation> GRN_NUM_Generation { get; set; }
        public virtual DbSet<GRN_SKU_Line_Items> GRN_SKU_Line_Items { get; set; }
        public virtual DbSet<Intermediate_DC> Intermediate_DC { get; set; }
        public virtual DbSet<Invoice_Collection> Invoice_Collection { get; set; }
        public virtual DbSet<Invoice_Collection_Excel_Tracking> Invoice_Collection_Excel_Tracking { get; set; }
        public virtual DbSet<Invoice_Collection_Num_Gen> Invoice_Collection_Num_Gen { get; set; }
        public virtual DbSet<Invoice_Collection_Tracking> Invoice_Collection_Tracking { get; set; }
        public virtual DbSet<Invoice_Creation> Invoice_Creation { get; set; }
        public virtual DbSet<Invoice_Line_item> Invoice_Line_item { get; set; }
        public virtual DbSet<Invoice_NUM_Generation> Invoice_NUM_Generation { get; set; }
        public virtual DbSet<Label_Fields> Label_Fields { get; set; }
        public virtual DbSet<Location_Master> Location_Master { get; set; }
        public virtual DbSet<Material_Master> Material_Master { get; set; }
        public virtual DbSet<Material_Master_Num_Gen> Material_Master_Num_Gen { get; set; }
        public virtual DbSet<MaterialSource> MaterialSources { get; set; }
        public virtual DbSet<Menu_Master> Menu_Master { get; set; }
        public virtual DbSet<Multiple_CSI_tracking> Multiple_CSI_tracking { get; set; }
        public virtual DbSet<PaymentCycle> PaymentCycles { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<Physical_Stock> Physical_Stock { get; set; }
        public virtual DbSet<PinCode> PinCodes { get; set; }
        public virtual DbSet<PO_NUM_Generation> PO_NUM_Generation { get; set; }
        public virtual DbSet<PO_Rate_Change_Audit> PO_Rate_Change_Audit { get; set; }
        public virtual DbSet<PO_RequitionedBy> PO_RequitionedBy { get; set; }
        public virtual DbSet<PO_type> PO_type { get; set; }
        public virtual DbSet<Printed_Barcode_Details> Printed_Barcode_Details { get; set; }
        public virtual DbSet<Purchase_Order> Purchase_Order { get; set; }
        public virtual DbSet<Purchase_Order_Line_item> Purchase_Order_Line_item { get; set; }
        public virtual DbSet<Rate_Template> Rate_Template { get; set; }
        public virtual DbSet<Rate_Template_Line_item> Rate_Template_Line_item { get; set; }
        public virtual DbSet<Rate_Template_Num_Gen> Rate_Template_Num_Gen { get; set; }
        public virtual DbSet<Region_Master> Region_Master { get; set; }
        public virtual DbSet<Role_Master> Role_Master { get; set; }
        public virtual DbSet<Role_Menu_Access> Role_Menu_Access { get; set; }
        public virtual DbSet<Role_User_Access> Role_User_Access { get; set; }
        public virtual DbSet<Route_Area_Master> Route_Area_Master { get; set; }
        public virtual DbSet<Route_Master> Route_Master { get; set; }
        public virtual DbSet<Route_Master_Auto_Num_Gen> Route_Master_Auto_Num_Gen { get; set; }
        public virtual DbSet<Sales_Route_Mapping> Sales_Route_Mapping { get; set; }
        public virtual DbSet<SKU_Main_Group> SKU_Main_Group { get; set; }
        public virtual DbSet<SKU_Main_Sub_Mapping> SKU_Main_Sub_Mapping { get; set; }
        public virtual DbSet<SKU_Master> SKU_Master { get; set; }
        public virtual DbSet<SKU_Sub_Group> SKU_Sub_Group { get; set; }
        public virtual DbSet<ST_NUM_Generation> ST_NUM_Generation { get; set; }
        public virtual DbSet<STI_Line_item> STI_Line_item { get; set; }
        public virtual DbSet<Stirnkage_Summary> Stirnkage_Summary { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Stock_Code_Num_Gen> Stock_Code_Num_Gen { get; set; }
        public virtual DbSet<Stock_Convertion_Tracking> Stock_Convertion_Tracking { get; set; }
        public virtual DbSet<Stock_Transaction> Stock_Transaction { get; set; }
        public virtual DbSet<Stock_Transfer_Indent> Stock_Transfer_Indent { get; set; }
        public virtual DbSet<Stock_Xfer_Dispatch_Num_Gen> Stock_Xfer_Dispatch_Num_Gen { get; set; }
        public virtual DbSet<Strinkage_Stock_Adj_Num_Gen> Strinkage_Stock_Adj_Num_Gen { get; set; }
        public virtual DbSet<Strinkage_Stock_Adjustement> Strinkage_Stock_Adjustement { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Supplier_Code_Num_Gen> Supplier_Code_Num_Gen { get; set; }
        public virtual DbSet<Sync_Checking> Sync_Checking { get; set; }
        public virtual DbSet<Sync_Checking_Line_item> Sync_Checking_Line_item { get; set; }
        public virtual DbSet<TALLY_MAPPING> TALLY_MAPPING { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<User_DC_Access> User_DC_Access { get; set; }
        public virtual DbSet<User_Details> User_Details { get; set; }
        public virtual DbSet<User_Location_Access> User_Location_Access { get; set; }
        public virtual DbSet<VoucherType> VoucherTypes { get; set; }
        public virtual DbSet<Wastage_Auto_Num_Gen> Wastage_Auto_Num_Gen { get; set; }
        public virtual DbSet<Wastage_Creation> Wastage_Creation { get; set; }
        public virtual DbSet<Wastage_Line_item> Wastage_Line_item { get; set; }
        public virtual DbSet<Wastage_Supplier_Info> Wastage_Supplier_Info { get; set; }
        public virtual DbSet<Stock_History> Stock_History { get; set; }
        public virtual DbSet<DCDASHBOARD_CSI2_CUST> DCDASHBOARD_CSI2_CUST { get; set; }
        public virtual DbSet<DCDASHBOARD_CSI2_CUST_PERCENTBASE> DCDASHBOARD_CSI2_CUST_PERCENTBASE { get; set; }
        public virtual DbSet<DCDASHBOARD_CSISTIADD> DCDASHBOARD_CSISTIADD { get; set; }
        public virtual DbSet<DCDASHBOARD_CSISTIFORGRAPH> DCDASHBOARD_CSISTIFORGRAPH { get; set; }
        public virtual DbSet<DCDASHBOARD_DISPATCH> DCDASHBOARD_DISPATCH { get; set; }
        public virtual DbSet<DCDASHBOARD_GRN> DCDASHBOARD_GRN { get; set; }
        public virtual DbSet<DCDASHBOARD_PO> DCDASHBOARD_PO { get; set; }
        public virtual DbSet<DCDASHBOARD_STI> DCDASHBOARD_STI { get; set; }
        public virtual DbSet<DCDASHBOARD_STOCK> DCDASHBOARD_STOCK { get; set; }
        public virtual DbSet<DCDASHBOARD_TOP5CUSTOMER> DCDASHBOARD_TOP5CUSTOMER { get; set; }
        public virtual DbSet<DCDASHBOARD_TOP5SKU> DCDASHBOARD_TOP5SKU { get; set; }
        public virtual DbSet<DCDASHBOARD_WASTAGE> DCDASHBOARD_WASTAGE { get; set; }
        public virtual DbSet<REPORT_12MONTH_BASED_ORDER> REPORT_12MONTH_BASED_ORDER { get; set; }
        public virtual DbSet<REPORT_CSI> REPORT_CSI { get; set; }
        public virtual DbSet<REPORT_CUSTOMER_FILL_RATE> REPORT_CUSTOMER_FILL_RATE { get; set; }
        public virtual DbSet<REPORT_DISPATCH> REPORT_DISPATCH { get; set; }
        public virtual DbSet<REPORT_DISPATCH_PACKTYPE_BASED> REPORT_DISPATCH_PACKTYPE_BASED { get; set; }
        public virtual DbSet<REPORT_MONTH_BASED_ORDER> REPORT_MONTH_BASED_ORDER { get; set; }
        public virtual DbSet<REPORT_OF_IN_OUT_SUMMARY> REPORT_OF_IN_OUT_SUMMARY { get; set; }
        public virtual DbSet<REPORT_PURCHASE> REPORT_PURCHASE { get; set; }
        public virtual DbSet<REPORT_STI_DISPATCH> REPORT_STI_DISPATCH { get; set; }
        public virtual DbSet<REPORT_STOCK_SUMMARY_UPDATED> REPORT_STOCK_SUMMARY_UPDATED { get; set; }
        public virtual DbSet<REPORT_WASTAGE_QTY> REPORT_WASTAGE_QTY { get; set; }
    
        public virtual int dispatch_proc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dispatch_proc");
        }
    
        public virtual int dispatchtostock_add(Nullable<int> dispatch_id)
        {
            var dispatch_idParameter = dispatch_id.HasValue ?
                new ObjectParameter("dispatch_id", dispatch_id) :
                new ObjectParameter("dispatch_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dispatchtostock_add", dispatch_idParameter);
        }
    
        public virtual int Grn_Detection_Service(Nullable<int> v_inward_id)
        {
            var v_inward_idParameter = v_inward_id.HasValue ?
                new ObjectParameter("V_inward_id", v_inward_id) :
                new ObjectParameter("V_inward_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Grn_Detection_Service", v_inward_idParameter);
        }
    
        public virtual int Stock123()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Stock123");
        }
    
        public virtual int Wastage_add(Nullable<int> v_Wastage_Id)
        {
            var v_Wastage_IdParameter = v_Wastage_Id.HasValue ?
                new ObjectParameter("V_Wastage_Id", v_Wastage_Id) :
                new ObjectParameter("V_Wastage_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Wastage_add", v_Wastage_IdParameter);
        }
    
        public virtual int Wastage_proc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Wastage_proc");
        }
    }
}
