//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multiple_CSI_tracking
    {
        public int Multiple_CSI_tracking_id { get; set; }
        public Nullable<int> No_of_CSI { get; set; }
        public string Uploaded_Excel_Display_Name { get; set; }
        public string Uploaded_Excel_Name { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreateBy { get; set; }
    }
}
