//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinCode
    {
        public int Code_Id { get; set; }
        public Nullable<double> PinCode1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    }
}
