//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_WASTAGE_QTY
    {
        public string DC_Code { get; set; }
        public string SKU_Category { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public double Floor { get; set; }
        public double Process { get; set; }
        public double C_QTY { get; set; }
        public double Total_qty { get; set; }
    }
}
