//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_CSI
    {
        public string DC_Code { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SKU_Category { get; set; }
        public double CSI_Qty { get; set; }
        public double CDN_Qty { get; set; }
        public double Invoice_Qty { get; set; }
        public double Customer_return_qty { get; set; }
        public double Fill_Rate { get; set; }
    }
}
