//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_STOCK_SUMMARY_UPDATED
    {
        public string DC_Code { get; set; }
        public string SKU_Category { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public double A_GRADE { get; set; }
        public double B_GRADE { get; set; }
        public double TOTAL_GRADE_VALUE { get; set; }
        public Nullable<int> Number_of_SKU { get; set; }
    }
}
