//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stirnkage_Summary
    {
        public int Stirnkage_Summary_Id { get; set; }
        public string Adjustment_Batch_Code { get; set; }
        public string DC_Code { get; set; }
        public Nullable<bool> Adjustment_Freeze { get; set; }
        public Nullable<bool> is_Adjusted { get; set; }
        public Nullable<System.DateTime> Closing_Date { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
