//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Transfer_Indent
    {
        public int STI_id { get; set; }
        public string STI_Number { get; set; }
        public Nullable<int> Indent_Raised_by_DC_Id { get; set; }
        public string Indent_Raised_by_DC_Code { get; set; }
        public Nullable<System.DateTime> STI_RLS_date { get; set; }
        public string SKU_Type { get; set; }
        public Nullable<int> SKU_Type_Id { get; set; }
        public Nullable<int> Material_Source_id { get; set; }
        public string Material_Source { get; set; }
        public string Intermediate_DC_Code { get; set; }
        public Nullable<int> Delivery_DC_id { get; set; }
        public string Delivery_DC_Code { get; set; }
        public string STI_Type { get; set; }
        public string STI_Delivery_cycle { get; set; }
        public Nullable<System.DateTime> DC_Delivery_Date { get; set; }
        public string STI_raise_by { get; set; }
        public string STI_Approve_by { get; set; }
        public Nullable<bool> STI_Approval_Flag { get; set; }
        public Nullable<System.DateTime> STI_Approved_date { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public string DeleteReason { get; set; }
        public Nullable<bool> is_Deleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> is_Syunc { get; set; }
    }
}
