//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TALLY_MAPPING
    {
        public int ID { get; set; }
        public string Activity { get; set; }
        public string Module_Name { get; set; }
        public string VOUCHER_TYPE { get; set; }
        public string LEDGER_CODE { get; set; }
        public string LEDGER_NAME { get; set; }
        public string GROUP_NAME { get; set; }
        public string COST_CENTRE_NAME { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
    }
}
