//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wastage_Supplier_Info
    {
        public int Id { get; set; }
        public Nullable<int> Wastage_Line_Id { get; set; }
        public string Wastage_Number { get; set; }
        public Nullable<int> SKU_ID { get; set; }
        public string SKU_Code { get; set; }
        public string SKU_Name { get; set; }
        public string DC_Code { get; set; }
        public Nullable<int> Supplier_Id { get; set; }
        public string Supplier_Code { get; set; }
        public string Supplier_name { get; set; }
        public string Grade { get; set; }
    }
}
