//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AutoGenerate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutoGenerate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessServices.AutoGenerate", typeof(AutoGenerate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDN.
        /// </summary>
        public static string CDT {
            get {
                return ResourceManager.GetString("CDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CI.
        /// </summary>
        public static string CIT {
            get {
                return ResourceManager.GetString("CIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSI.
        /// </summary>
        public static string CSIT {
            get {
                return ResourceManager.GetString("CSIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string CUST {
            get {
                return ResourceManager.GetString("CUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTK.
        /// </summary>
        public static string ESTT {
            get {
                return ResourceManager.GetString("ESTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRN.
        /// </summary>
        public static string GRNT {
            get {
                return ResourceManager.GetString("GRNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVC.
        /// </summary>
        public static string INVCT {
            get {
                return ResourceManager.GetString("INVCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INV.
        /// </summary>
        public static string INVT {
            get {
                return ResourceManager.GetString("INVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string MT {
            get {
                return ResourceManager.GetString("MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO.
        /// </summary>
        public static string POT {
            get {
                return ResourceManager.GetString("POT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RI.
        /// </summary>
        public static string RIT {
            get {
                return ResourceManager.GetString("RIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STN.
        /// </summary>
        public static string SDT {
            get {
                return ResourceManager.GetString("SDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI.
        /// </summary>
        public static string SI {
            get {
                return ResourceManager.GetString("SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI.
        /// </summary>
        public static string SIT {
            get {
                return ResourceManager.GetString("SIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STI.
        /// </summary>
        public static string STIT {
            get {
                return ResourceManager.GetString("STIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STK.
        /// </summary>
        public static string STKT {
            get {
                return ResourceManager.GetString("STKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STRK.
        /// </summary>
        public static string STRKT {
            get {
                return ResourceManager.GetString("STRKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string SUPT {
            get {
                return ResourceManager.GetString("SUPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string TT {
            get {
                return ResourceManager.GetString("TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS.
        /// </summary>
        public static string WST {
            get {
                return ResourceManager.GetString("WST", resourceCulture);
            }
        }
    }
}
