//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SKU_Category {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SKU_Category() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessServices.SKU_Category", typeof(SKU_Category).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exotic.
        /// </summary>
        public static string ExoticType {
            get {
                return ResourceManager.GetString("ExoticType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruit.
        /// </summary>
        public static string FruitType {
            get {
                return ResourceManager.GetString("FruitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herb.
        /// </summary>
        public static string HerbType {
            get {
                return ResourceManager.GetString("HerbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leafy.
        /// </summary>
        public static string LeafyType {
            get {
                return ResourceManager.GetString("LeafyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperate.
        /// </summary>
        public static string TemperateType {
            get {
                return ResourceManager.GetString("TemperateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tropical.
        /// </summary>
        public static string TropicalType {
            get {
                return ResourceManager.GetString("TropicalType", resourceCulture);
            }
        }
    }
}
